name: Build daily alpha

on:
  schedule:
    - cron: '0 * * * *'

jobs:

  configure-params:
    uses: ai91/majordomo-docker/.github/workflows/build_configure_params.yml@main

  check-image-existence:
    name: Check existence of docker tag
    runs-on: ubuntu-latest
    needs: configure-params
    outputs:
      run_rest_jobs: ${{ steps.set_output.outputs.run_jobs }}
    steps:
      - name: Check
        shell: bash
        run: |
          echo "alpha_php7_tag = ${{ needs.configure-params.outputs.alpha_php7_tag }}"
          docker manifest inspect ai91/majordomo-docker:${{ needs.configure-params.outputs.alpha_php7_tag }} > /dev/null 2>&1 && echo ("run_jobs=false" || echo "run_jobs=true") >> "$GITHUB_OUTPUT"

  trigger-build:
    name: Trigger build
    needs: [configure-params, check-image-existence]
    if: needs.check-image-existence.outputs.run_jobs == 'true'
    uses: ai91/majordomo-docker/.github/workflows/build_alpha.yml@main
    secrets: inherit

