name: Configure params with php versions and tags

on:
  workflow_call:
    outputs:
      php7_version:
        value: ${{ jobs.configure.outputs.php7_version }}
      php8_version:
        value: ${{ jobs.configure.outputs.php8_version }}
      master_php7_tag:
        value: ${{ jobs.configure.outputs.master_php7_tag }}
      master_php8_tag:
        value: ${{ jobs.configure.outputs.master_php8_tag }}
      alpha_php7_tag:
        value: ${{ jobs.configure.outputs.alpha_php7_tag }}
      alpha_php8_tag:
        value: ${{ jobs.configure.outputs.alpha_php8_tag }}

jobs:

  configure:

    runs-on: ubuntu-latest
    outputs:
      php7_version: ${{ steps.generate.outputs.php7_version }}
      php8_version: ${{ steps.generate.outputs.php8_version }}
      master_php7_tag: ${{ steps.generate.outputs.master_php7_tag }}
      master_php8_tag: ${{ steps.generate.outputs.master_php8_tag }}
      alpha_php7_tag: ${{ steps.generate.outputs.alpha_php7_tag }}
      alpha_php8_tag: ${{ steps.generate.outputs.alpha_php8_tag }}

    steps:
    - id: generate
      name: Generate tags
      shell: bash
      run: |
        php7=7.4.33
        php8=8.4.1
        echo "php7_version=${php7}" >> $GITHUB_OUTPUT
        echo "php8_version=${php8}" >> $GITHUB_OUTPUT
        echo "master_php7_tag=master_$(git ls-remote https://github.com/sergejey/majordomo refs/heads/master | cut -c 1-7 | tr '/a-z/' '/A-Z/')_php${php7}" >> "$GITHUB_OUTPUT"
        echo "master_php8_tag=master_$(git ls-remote https://github.com/sergejey/majordomo refs/heads/master | cut -c 1-7 | tr '/a-z/' '/A-Z/')_php${php8}" >> "$GITHUB_OUTPUT"
        echo "alpha_php7_tag=alpha_$(git ls-remote https://github.com/sergejey/majordomo refs/heads/alpha | cut -c 1-7 | tr '/a-z/' '/A-Z/')_php${php7}" >> "$GITHUB_OUTPUT"
        echo "alpha_php8_tag=alpha_$(git ls-remote https://github.com/sergejey/majordomo refs/heads/alpha | cut -c 1-7 | tr '/a-z/' '/A-Z/')_php${php8}" >> "$GITHUB_OUTPUT"
