name: Build daily master

on:
  schedule:
    - cron: '0 2 * * *'

jobs:

  configure-params:
    uses: ai91/majordomo-docker/.github/workflows/build_configure_params.yml@main

  check-image-existence:
    name: Check existence of docker tag
    runs-on: ubuntu-latest
    needs: configure-params
    outputs:
      run_trigger_build: ${{ steps.check.outputs.trigger_build }}
    steps:
      - name: Check
        id: check
        shell: bash
        run: |
          echo "master_php7_tag = ${{ needs.configure-params.outputs.master_php7_tag }}"
          docker manifest inspect ai91/majordomo-docker:${{ needs.configure-params.outputs.master_php7_tag }} > /dev/null 2>&1 && (echo "trigger_build=false"  >> "$GITHUB_OUTPUT") || (echo "trigger_build=true" >> "$GITHUB_OUTPUT")

  trigger-build:
    name: Trigger build master
    needs: [configure-params, check-image-existence]
    if: "${{ needs.check-image-existence.outputs.run_trigger_build == 'true' }}"
    uses: ai91/majordomo-docker/.github/workflows/build_master.yml@main
    secrets: inherit

