name: Build alpha with php 7

on:
  workflow_call:
    inputs:
      php7_version:
        required: true
        type: string
      alpha_php7_tag:
        required: true
        type: string

jobs:

  build:
    name: Build alpha php7

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set enviroment variables
      shell: bash
      run: echo "phpTag=${{ inputs.php7_version }}-apache" >> "$GITHUB_ENV"
    - name: Generate Dockerfile
      run: ./generate-docker.sh
    - uses: actions/checkout@v4
      with:
        repository: sergejey/majordomo
        ref: alpha
        path: majordomo
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm/v5,linux/386,linux/arm64/v8,linux/arm/v7,linux/s390x,linux/ppc64le,linux/amd64,linux/mips64le
        install: true
        driver: docker-container
        driver-opts: network=host
    - name: Force Buildx Builder to Start
      run: docker buildx inspect --bootstrap
    - name: Increase BuildKit Memory Limit
      run: |
        sleep 10  # Give BuildKit time to start
        CONTAINER_ID=$(docker ps --filter "name=buildx_buildkit" --format "{{.ID}}")
        if [ -n "$CONTAINER_ID" ]; then
          docker update --memory 8g --memory-swap 8g --cpus 4 $CONTAINER_ID
        else
          echo "Error: BuildKit container not found!"
          exit 1
        fi
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      env:
        BUILDKIT_PROGRESS: plain
      with:
        context: .
        builder: limitedbuilder
        platforms: linux/arm/v5,linux/386,linux/arm64/v8,linux/arm/v7,linux/s390x,linux/ppc64le,linux/amd64,linux/mips64le
        build-args: |
          MAKEFLAGS=-j1
        push: true
        tags: ai91/majordomo-docker:${{ inputs.alpha_php7_tag }}, ai91/majordomo-docker:alpha_php7, ai91/majordomo-docker:alpha
    - name: Clean Up Docker Buildx
      run: docker buildx rm
