name: Build master

on:
  workflow_dispatch:
  workflow_call:

jobs:

  configure-params:
    uses: ai91/majordomo-docker/.github/workflows/build_configure_params.yml@main

  build-php7:
    name: Trigger build master php7
    needs: [configure-params]
    uses: ai91/majordomo-docker/.github/workflows/build_master_7.yml@main
    with:
      php7_version: ${{ needs.configure-params.outputs.php7_version }}
      master_php7_tag: ${{ needs.configure-params.outputs.master_php7_tag }}
    secrets: inherit

  build-php8:
    name: Trigger build master php8
    needs: [configure-params]
    uses: ai91/majordomo-docker/.github/workflows/build_master_8.yml@main
    with:
      php8_version: ${{ needs.configure-params.outputs.php8_version }}
      master_php8_tag: ${{ needs.configure-params.outputs.master_php8_tag }}
    secrets: inherit
