name: Build alpha

on: workflow_dispatch

jobs:

  build-php7:
    uses: ai91/majordomo-docker/.github/workflows/build_alpha_7.4.yml@main
    secrets: inherit

  build-php8:
    uses: ai91/majordomo-docker/.github/workflows/build_alpha_8.3.yml@main
    secrets: inherit
