name: Docker Image CI

on: workflow_dispatch

jobs:

  build_alpha_8.3:

    runs-on: ubuntu-latest

    steps:
    - name: Set enviroment variables
      shell: bash
      run: |
        phpVersion=8.3.9
        echo "phpTag=${phpVersion}-apache" >> "$GITHUB_ENV"
        echo "ALPHA_HASH=alpha_$(git ls-remote https://github.com/sergejey/majordomo refs/heads/alpha | cut -c 1-7)_php${phpVersion}" | tr '/a-z/' '/A-Z/' >> "$GITHUB_ENV"
    - uses: actions/checkout@v4
    - name: Generate Dockerfile
      run: ./generate-docker.sh
    - uses: actions/checkout@v4
      with:
        repository: sergejey/majordomo
        ref: alpha
        path: majordomo
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        #platforms: linux/386
        platforms: linux/arm/v5,linux/386,linux/arm64/v8,linux/arm/v7,linux/s390x,linux/ppc64le,linux/amd64,linux/mips64le
        push: true
        tags: ai91/majordomo-docker:${{env.ALPHA_HASH}}, ai91/majordomo-docker:alpha_latest
