name: Build alpha with php 7

on:
  workflow_call:
    inputs:
      php7_version:
        required: true
        type: string
      alpha_php7_tag:
        required: true
        type: string

jobs:

  build:
    name: Build alpha php7

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set enviroment variables
      shell: bash
      run: echo "phpTag=${{ inputs.php7_version }}-apache" >> "$GITHUB_ENV"
    - name: Generate Dockerfile
      run: ./generate-docker.sh
    - uses: actions/checkout@v4
      with:
        repository: sergejey/majordomo
        ref: alpha
        path: majordomo
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.3.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.8.0
      with:
        platforms: linux/arm/v5,linux/386,linux/arm64/v8,linux/arm/v7,linux/s390x,linux/ppc64le,linux/amd64,linux/mips64le
        install: true
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6.10.0
      env:
        BUILDKIT_PROGRESS: plain
      with:
        context: .
        platforms: linux/arm/v5,linux/386,linux/arm64/v8,linux/arm/v7,linux/s390x,linux/ppc64le,linux/amd64,linux/mips64le
        push: true
        tags: ai91/majordomo-docker:${{ inputs.alpha_php7_tag }}, ai91/majordomo-docker:alpha_php7, ai91/majordomo-docker:alpha
    - name: Clean Up Docker Buildx
      run: docker buildx rm
