name: Build master with php 7.4

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set enviroment variables
      shell: bash
      run: |
        phpVersion=7.4.25
        echo "phpTag=${phpVersion}-apache" >> "$GITHUB_ENV"
        echo "MASTER_HASH=master_$(git ls-remote https://github.com/sergejey/majordomo refs/heads/master | cut -c 1-7 | tr '/a-z/' '/A-Z/')_php${phpVersion}" >> "$GITHUB_ENV"
    - uses: actions/checkout@v4
    - name: Generate Dockerfile
      run: ./generate-docker.sh
    - uses: actions/checkout@v4
      with:
        repository: sergejey/majordomo
        ref: master
        path: majordomo
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        #platforms: linux/386
        platforms: linux/arm/v5,linux/386,linux/arm64/v8,linux/arm/v7,linux/s390x,linux/ppc64le,linux/amd64,linux/mips64le
        push: true
        tags: ai91/majordomo-docker:${{env.MASTER_HASH}}, ai91/majordomo-docker:latest_php7
